driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1
  - name: centos-6.5
  - name: debian-7.4

suites:
  - name: default
    run_list:
      - recipe[anselmo_pfeifer::default]
