Vagrant.configure("2") do |config|
  	config.vm.box = "precise64.box"
  	config.vm.box_url = "http://files.vagrantup.com/precise64.box"
	config.vm.network "forwarded_port", guest: 80, host: 80
	config.vm.provider :virtualbox do |vb|
    	vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    	vb.customize ["modifyvm", :id, "--memory", 512]
    	vb.customize ["modifyvm", :id, "--name", "financeiro"]
	config.vm.provision "shell", path: "script.sh"
	end
end
